[build]
  command = "npm run build"
  publish = "www"


[template.environment]
  NODE_ENV=development
  MAP_URL='Sitemap https://www.sites.dev/sitemap.xml'
  CONTACT_EMAIL=xxxxx@mail.com
  FORM_PROVIDER=web3forms
  WEBFORM_SUCCESS=https://web3forms.com/success
  #NETLIFY_SUCCESS=/thank-you/
  #CONTACT_PROVIDER=web3forms
