[build]
  command = "eleventy"
  publish = "www"


[template.environment]
  NODE_ENV =  "NODE environment"
  MAP_URL = "Site map (Sitemap https://www.xxx.com/sitemap.xml)"
  CONTACT_EMAIL = "Contact email"
  FORM_PROVIDER = "Contact form provider (netlify/webforms)"
  CONTACT_SUCCESS = "/thank-you" (thank you page)
