[build]
  command = "npm run build"
  publish = "www"


[template.environment]
  NODE_ENV =  "NODE environment"
  MAP_URL = "Site map url"
  CONTACT_EMAIL = "Contact email"
  FORM_PROVIDER = "contact form provider"
  CONTACT_SUCCESS = "/thank-you"
  CONTACT_PROVIDER ="Contact from provider"
